name: Scan_expresspros.com
on: 
  workflow_dispatch: {}
  schedule:	##This cron expression triggers the workflow At 12:01 AM (UTC) every day
    - cron: '1 0 * * *'
jobs:
  dastardly-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Run Dastardly Action Step
        continue-on-error: true 
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'https://www.expresspros.com'
      - name: Publish Test Report
        if: always()
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/dastardly-report.xml'
          require_Tests: true
permissions:
    contents: read
    issues: read
    checks: write
    pull-requests: write
    id-token: write
