name: Dastardly Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dastardly-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Run Dastardly Action Step
        continue-on-error: true
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'https://reflik.com'

      - name: Publish Test Report
        if: always()
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/dastardly-report.xml'
          require_tests: true
